blog_yard/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from blogs import views
urlpatterns = [
    path('',views.Index,name='index'),
    path('admin/', admin.site.urls),
    path('blogs/',include('blogs.urls')),
     
    path('register/',views.RegisterView,name='register'),

    #ajax urls
    path('ajax/user_exists',views.check_user_exists,name='user_exists'),
    
] 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/urls.py
from django.urls import path, include
from django.contrib import admin

from . import views
# app_name='blogs'

urlpatterns = [
    path('', views.BlogView.as_view(), name='index'),
    path('login/', views.LoginView, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('user special/',views.HomeView,name='home'),
    path('',views.BlogView.as_view(),name='blog_index'),
    path('profile/<slug:username>/',views.Profile,name='profile'),


    path('read/<int:pk>/',views.FullBlogView.as_view(),name='full-blog'),

    #ajax urls
    
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.conf import settings
import datetime
import dateutil
from django import forms 

# Create your models here.
class BlogUser(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    picture=models.ImageField(upload_to='user_pic')
    bio= models.TextField(max_length=256,blank=True)
    date_of_birth=models.DateField()

    def get_absolute_url(self):
        return reverse('blogs:profile',kwargs={'username':self.user.username})

#    def get_user_age(self,born):

    def get_user_age(self):
    # Get the current date
        new_date = datetime.date(
            self.date_of_birth.year, self.date_of_birth.month, self.date_of_birth.day)
        now = datetime.date.today()
        print('\n\n\n\n\n\n',type(new_date),'\n',type(now))
        # Get the difference between the current date and the birthday
        
        age = dateutil.relativedelta.relativedelta(now, new_date)
        age = age.years
        print(age, '\n\n\n\n\n\n\n\n')
        return str(age)

    def __str__(self):
        return self.user.username

class Blog(models.Model):
    author=models.ForeignKey(BlogUser,on_delete=models.CASCADE)
    title=models.CharField(max_length=128)
    post_date=models.DateField(default=datetime.date.today)
    post_time=models.TimeField(default=datetime.datetime.now().time)
    content=models.TextField(max_length=1256)
    picture = models.ImageField(upload_to='blog_pic')


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        # return reverse('blogs:profile', kwargs={'username': self.user.username})
        # pass
        return reverse('full-blog',kwargs={'pk':self.id})

blogs/forms.py
from django import forms
from django.core import validators
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.urls import path
from django.shortcuts import reverse

from django.contrib.auth.models import User
from .models import BlogUser,Blog

class UserForm(forms.ModelForm):
    helper = FormHelper()
    helper.form_class = 'form-horizontal'
    helper.form_id='regForm'
    helper.label_class='col-lg-2'
    helper.field_class='col-lg-8'
    helper.form_method='post'
    helper.form_action = 'register'

    helper.add_input(Submit('submit_user_details','Sign Up',css_class='btn btn-success'))
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model=User
        
        fields= ('username','first_name','last_name','email','password')


class UserProfileForm(forms.ModelForm):
    helper = FormHelper()
    helper.form_class = 'form-horizontal'
    helper.form_id = 'profileForm'
    helper.label_class = 'col-lg-2'
    helper.field_class = 'col-lg-8'
    helper.form_method = 'post'
    # helper.form_tag= False
    # helper.form_action = reverse('blogs:profile', kwargs={
                                #  'username': self.user.username})
    # helper.form_action =  'profile'   #path('profile/<slug:username>/', views.Profile, name='profile')

    # helper.add_input(Submit('submit_profile_details',
                            # 'Save', css_class='btn btn-success'))

    class Meta:
        model = BlogUser
        fields = ('picture','bio','date_of_birth')


class PostBlogForm(forms.ModelForm):
    helper = FormHelper()
    helper.form_class = 'form-inline'
    helper.form_id = 'profileForm'
    helper.label_class = 'col-lg-2'
    helper.field_class = 'col-lg-8'
    helper.form_method = 'post'
    class Meta:
        model= Blog
        fields=('title','content')

blogs/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, TemplateView, DetailView, View
from django.contrib import messages

#from django.contrib import sessions
from django.contrib.auth.models import User
from .forms import UserForm, UserProfileForm
from .models import  BlogUser,Blog

# import datetime
# import dateutil
# Create your views here.

# @login_required
# def Index(request):
#    return render(request,'index.html',{})

import string
def Index(request):
    
    all_blogs = Blog.objects.all()
    # template=loader.get_template('index.html')
    context = {
        'all_blogs': all_blogs,
        #       'session_user': user
        'chars': lambda x: x.replace(' ','-')   

    }
    return render(request, 'index.html', context)


class BlogView(ListView):
    template_name = 'index.html'
    context_object_name = 'all_blogs'

    def get_queryset(self):
        return Blog.objects.all()

class FullBlogView(DetailView):
    model = Blog
    template_name = 'full-blog.html'
    fields = '__all__'
    context_object_name = 'post'



@login_required
def user_logout(request):
    logout(request)
    try:
        del request.session['logged']
    except:
        pass    
    return HttpResponseRedirect(reverse('index'))


@login_required
def HomeView(request):
    name=request.session['logged']
    return HttpResponse("<h1>Welcome!{}</h1>".format(name))


def LoginView(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                request.session['logged'] = username
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("User not active")
        else:
            print("someone tried to login and failed")
            print("Username: {} and Password: {}".format(username, password))
            
            return render(request,'login.html',{'wrong_details':'invalid login details supplied'})
    else:
        return render(request,'login.html',{})


def check_user_exists(request):
    username= request.GET.get('username')
    if User.objects.filter(username=username).exists():
        error_msg= "user with the same name already exists."
        usr= username
    else:
        error_msg= ""
        usr=""
    data = {'error_msg':error_msg,'usr':usr}
    return  JsonResponse(data)  


def RegisterView(request):
    registered = False
    if request.method == 'POST':
        user = UserForm(data=request.POST)

        if user.is_valid():
            user_data = user.save()
            user_data.set_password(user_data.password)
            user_data.save()
            # blog_user = authenticate(username=request.POST.username,password=request.POST.password)

            registered = True
    else:
        user = UserForm()
    return render(request, 'register.html', {'user': user, 'registered': registered})

# @login_required
# class ProfileView(View):
#     model=BlogUser
#     template_name='profile.html'
#     context_object_name='blog_user'

import sys 
from django.db.models import query
# @login_required
def Profile(request, username):
    user = get_object_or_404(User, username=username)
    user_p=None
    user_age=0
    user_profile = ''
    try:
        user_p = BlogUser.objects.get(user_id=user.id)
        user_age=user_p.get_user_age()
        
    except:
        print('\n\n\n\n\n', sys.exc_info(), '\n\n\n\n\n\n\n\n')
        if request.method == "POST":
            
            user_profile = UserProfileForm(request.POST,request.FILES)

            if user_profile.is_valid():
                profile = user_profile.save(commit=False)
                profile.user = user

                if 'picture' in request.FILES:
                    profile.picture = request.FILES['picture']
                profile.save()
                # print('\n\n\n\n\nuser profile saved.....\n\n\n\n\n\n\n\n')
                # return render(request,'profile.html')
                return HttpResponseRedirect(redirect('profile',username=user.username))
                # return reverse('profile')    
            # else:
                # validation_error = user_profile.errors
        else:
            user_profile = UserProfileForm()
    finally:        
        return render(request, 'profile.html', {'blog_user': user, 'age':user_age,'user_profile': user_profile, 'user_p': user_p})





#custom decorator for logged user check
# def is_logged_user(*args, **kwargs):
#     if 'request' in kwargs:
#         session_user=request.session['logged']

blogs/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>BlogYard-{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <link rel="stylesheet" type="text/css" media="screen" href="main.css" /> -->
    <link href="https://fonts.googleapis.com/css?family=Acme|Anton|Gloria+Hallelujah|Pacifico|Satisfy" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
    <!-- <script
        src="http://code.jquery.com/jquery-3.3.1.js"
        integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
        crossorigin="anonymous">
    </script> -->
    <script src="http://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>    

    <!-- <script src="main.js"></script> -->
    {%  block javascript %} {% endblock %}
    <style>
        .mycontainer
        {
            width: inherit;
            padding-left: 25px;
            padding-top:15px;
            padding-bottom: 15px;
            border-radius: 25px 25px;
            padding-right: 25px;
            color:azure;
                        
            
            background-color: rgba(255, 255, 255, 0.2);
            /* box-shadow: 15px 15px 35px 5px #888888; */
        }
        .mybody {
            background-size: 100%;
            background-image: url("{% static 'blogs/galaxy_background.jpg' %}");

            align:center;
            width:100%;
            padding: 25px 125px; 
        }
    </style>

</head>
<body class=mybody>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="{% url 'index' %}"><span style="color: aqua;font-family: 'Pacifico';font-size: 30px;text-shadow: 5px 5px 10px rgb(0, 0, 0);">Blog</span><span style="color:chocolate;font-family: 'Acme';font-size: 30px;text-shadow: 5px 5px 10px rgb(0, 0, 0);">Yard</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#"><span style="font-family: Satisfy;font-size:24px">Sport</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#"><span style="font-family: Satisfy;font-size:24px">Fashion</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#"><span style="font-family: Satisfy;font-size:24px">Lifestyle</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#"><span style="font-family: Satisfy;font-size:24px">Gadgets</span></a>
                </li>

            </ul>
        
        <!-- <form class="form-inline"> -->
            

            {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'profile' user.username %}">@{{ user.username }}</a>
            <a class="nav-link" href="{% url 'logout' %}">logout</a>
            {% else %}
            <a class="nav-link" href="{% url 'register' %}">Register</a>
            <a class="nav-link" href="{% url 'login' %}">login</a>
            {% endif %}
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            <!-- <button class="btn btn-outline-light" type="submit">Log Out</button> -->

        <!-- </form> -->
        </div>
    </nav>
    <br><br><br><br>
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>


    
</body>
</html>

blogs/templates/full-blog.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block title %}User Profile{% endblock %}
{% block body %}

    <div class="jumbotron">
            <p><h1>{{post.title}}</h1></p>
            <p><h3>@{{post.user}}</h3></p>
            <p><h4>{{post.post_date}}&nbsp;&nbsp;{{post.post_time}}</h4></p>
            <hr>
            <p>
                <h3>{{post.content}}</h3>
            </p>



    </div>


{% endblock %}

blogs/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Home {% endblock %}
{% block body %}
{% if user.is_authenticated %}
    
    <div id='blogform' class="mycontainer">
        <div class="container">
            <form onsubmit="return false" class="form-group" method="post">
                <div class="row">
                    <div id='col1' class="col-sm-2" style="align-self: center">    
                        <img src= "{% if not user.picture %}{% static 'blogs/default.png' %}{%else%}{% static '../media/blogs/'' %}{{user.picture}}{% endif %}" width="100px" height="100px">
                    </div>
                    <div id='col2' class="col-lg-8" style="align-self: center">
                        <div class="row">
                            <h1 style="font-family:'Anton';font-size: 34px;">{{user.username}}</h1>
                        </div>
                        <div class="row">
                            
                        </div>    
                    </div>    
                </div>
            </form>    
        </div>

    </div>
{% endif%}
        {% if all_blogs %}
            {% for post in all_blogs %}
            <div class ="mycontainer">
                <div class='jumbotron'>
                  <!-- <ul> -->
                        <p><a href="{% url 'full-blog' post.id %}" style="text-decoration: none;color:black"><h1>{{post.title}}</h1></a> </p>
                        <p><a href="{% url 'profile' post.user %}"><h4>@{{post.user}}</h4></a></p>
                        <p><small>{{post.post_date}}</small>&nbsp;&nbsp;<small>{{post.post_time}}</small></p>
                        
                  <!-- </ul>   -->
                </div>
            </div>    
            {% endfor %}
        {% else %}
        <div class="mycontainer">
            <h1 style="font-family: 'Satisfy';font-size: 30px">Welcome to the BlogYard.lorem ipsum Lorem ipsum dolor, sit amet consectetur adipisicing elit. Omnis hic id fuga assumenda. Ipsa, delectus! Officia facere vitae id voluptates voluptatum necessitatibus odit optio facilis, natus ipsa quas quia ea. </h1>
        </div>
        {% endif %}
    
{% endblock %}

blogs/templates/login.html
{% extends 'base.html' %} 
{% block title %} Login Page {% endblock %} 



{% block body %}
<div class="jumbotron">
    <h1>Please login</h1>
    <hr><br>
    <form action="{% url 'login' %}" method="POST" class="form-horizontal">
        {% csrf_token %}
        <table>
            <tr>
                <div class="">
                    <td>
                        <label class="col-lg-2" for="username">Username:</label>
                    </td>
                    <td class="col-lg-12">
                        <input class="form-control col-lg-8" type="text" name="username" placeholder="Enter your Username">
                    </td>
                    
                <!-- </div> -->
            </tr>
            <tr>
                <!-- <div class="form-group"> -->
                    <td>
                        <label class="col-lg-2" for="password">Password:</label>
                    </td>
                    <td class="col-lg-12">
                        <input class="form-control col-lg-8" type="password" name="password">
                    </td>
                </div>
            </tr>
            <tr>
                <td></td>
                
                <td>
                    <br>
                    &nbsp;&nbsp;&nbsp;<input class="btn btn-success col-sm-2" type="submit" value="Login">
                    <button class="btn btn-default col-sm-2" type="reset" value="Cancel">Cancel</button>
                    <a href="{% url 'register' %}" class="btn btn-info col-sm-2" role="button">Sign Up</a>
                </td>
            </tr>
        </table>

    </form>

</div>

{% endblock %}

{% block javascript %}
    <script type="text/javascript">
        {% if wrong_details %}
            alert("{{wrong_details}}");
        {% endif %}    
    </script>
{% endblock %}

blogs/templates/profile.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block title %}User Profile{% endblock %}
{% block body %}
    
        <div class='row justify-content-md-center'>
            {% if user_p == None %}
            <div class='col col-sm-4'>
                <img style="width: 200px;height:200px;padding:5px;border-radius:50%" src="{% static 'blogs/default.png' %}" alt="default profile pic"/> 
            </div>
            <div class='col col-sm-8'>
                <form method="POST" id='profileForm' action="{% url 'profile' blog_user.username %}" enctype="multipart/form-data">
                    {% crispy user_profile %} {% csrf_token %}
                    <input type="submit" form='profileForm' name="submit_profile_details" value="Save" class="btn btn-primary btn btn-success"
                        id="submit-id-submit_profile_details">
                </form>
            </div>
            {% else %}
            <div class='col-sm'>
                <img style="width: 200px;height:200px;padding:5px;border-radius:50%" src="{% static '../media/blogs/' %}{{user_p.picture}}" alt="" />
            </div>
             
            <div class='col-sm-8' style="padding-top: 15px">
                <p>{{blog_user.username}}</p>
                <p>{{blog_user.first_name}}&nbsp;{{blog_user.last_name}}</p>
                <p>{{blog_user.email}}</p>
                <p>{{user_p.bio}}</p>
                <p>{{age}}</p>
            </div>
            
            {% endif %}
        </div>

        <br>
        <div class='container'>
            <div class='row'>
                <!-- <form class='form-group' method="POST">
                    <label for='blog_title' class='col-form-label col-lg-2'>Title</label>
                    <input type="text" id='blog_title' class='col-lg-8' name='title' placeholder='Enter Title of blog here...'>
                    
                    
                    <input type="text" id='blog_content' class=
                </form> -->

            </div>
        </div>
    
{% endblock %}

blogs/templates/register.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block title %}Sign Up Page{% endblock %} 


{% block body %}
<script type="text/javascript">
    $(document).ready(function(){
        var hint_prev_str= $("#hint_id_username").text();
        console.log('hint_id_username:',hint_prev_str);
        $('#id_username').change(function(){
        
        $.ajax({
            type: "GET",
            contentType: "application/json; charset=utf-8",
            url: '/ajax/user_exists',
            async: true,
            data: {
                username: $("#id_username").val(),
                
            },
            success: function(response)
            {
                var str1= response['error_msg'];
                var usr= response['usr'];
                if (response['usr']) {
                    var str2 = "<strong style='color:red'><span style='color:blue'>" + usr+":</span> "+str1 + "</strong>";
                    $('#id_username').val("");  
                    $('#id_username').focus();
                    $('#id_username').removeClass('is-valid');
                    $('#id_username').addClass('is-invalid');
                }else{
                    $('#id_username').removeClass('is-invalid');
                    $('#id_username').addClass('is-valid');
                    
                    var str2 = hint_prev_str;
                }
                $('#hint_id_username').html(str2);
                
                
               
            },
            
            error: function ()
            {
            notify('Something went wrong');
            }
            });
        });
    });


</script>


<script>
    function PasswordValidityCheck(){
        var regularExpression = /^(?=.*[0-9])(?=.*[!@#$%^&*])[a-zA-Z0-9!@#$%^&*]{6,16}$/;
        var password_element = document.getElementById('id_password');
        $('#id_password').change(function(){
            var password=$('#id_password').val();
            if (!regularExpression.test(password)) {
                var password_error = "<strong id='password_error'  style='color:red'>password should contain atleast one digit, one Capital alphabet, and these [!@#$%^&*] symbols.</strong>";
                $('#id_password').val("");
                password_element.focus();
                $('#id_password').removeClass('is-valid');
                $('#id_password').addClass('is-invalid');
            }else{
                var password_error = "";
                $('#id_password').removeClass('is-invalid');
                $('#id_password').addClass('is-valid');
            }
            $('#password_error').text("");
            password_element.insertAdjacentHTML('afterend',password_error);
        });
    }
</script>


<script>
    $(document).ready(function(){
        PasswordValidityCheck();
        $('#id_confirm_password').change(function(){

            var password=$('#id_password').val();
            var verify_pass= $('#id_confirm_password').val();
            var confirm_password= document.getElementById('id_confirm_password');
            if (password!=verify_pass) {
                var conf_error="<strong id='conf_error' style='color:red'>password does not match.</strong>";
                $('#id_confirm_password').val("");
                $('#id_confirm_password').focus();
                $('#id_confirm_password').removeClass('is-valid');
                $('#id_confirm_password').addClass('is-invalid');
            } else {
                var conf_error = "";
                $('#id_confirm_password').removeClass('is-invalid');
                $('#id_confirm_password').addClass('is-valid');
            }
            $('#conf_error').text("");
            confirm_password.insertAdjacentHTML('afterend',conf_error);
        });
    });
</script>
<div class="jumbotron">
    {% if registered %}
        <h1 style="font-family: Satisfy;font-size:40px">Thank You for registering.</h1>
    {% else %}

        <h1 style="font-family: Pacifico;font-size:40px">Fill out this form.</h1><hr>
            {% crispy user %}
            {% csrf_token %}
    {% endif %}        
</div>
{% endblock %}